wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: xgboost
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1684443265
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      2:
      - 1
      - 5
      - 6
      - 11
      - 49
      4: 3.8.12
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
